replaceitem entity @c slot.inventory 0 air
replaceitem entity @c slot.inventory 1 air
replaceitem entity @c slot.inventory 2 air
replaceitem entity @c slot.inventory 3 air
replaceitem entity @c slot.inventory 4 air
replaceitem entity @c slot.inventory 5 air
replaceitem entity @c slot.inventory 6 air
replaceitem entity @c slot.inventory 7 air
replaceitem entity @c slot.inventory 8 air
replaceitem entity @c slot.inventory 9 air
replaceitem entity @c slot.inventory 10 air
replaceitem entity @c slot.inventory 11 air
replaceitem entity @c slot.inventory 12 air
replaceitem entity @c slot.inventory 13 air
replaceitem entity @c slot.inventory 14 air
replaceitem entity @c slot.inventory 15 air
replaceitem entity @c slot.inventory 16 air
replaceitem entity @c slot.inventory 17 air
replaceitem entity @c slot.inventory 18 air
replaceitem entity @c slot.inventory 19 air
replaceitem entity @c slot.inventory 20 air
replaceitem entity @c slot.inventory 21 air
replaceitem entity @c slot.inventory 22 air
replaceitem entity @c slot.inventory 23 air
replaceitem entity @c slot.inventory 24 air
replaceitem entity @c slot.inventory 25 air
replaceitem entity @c slot.inventory 26 air