# Executing as the player
# Do not edit - Automatically generated from scoreboard.txt

scoreboard players set @s flying_enabled 0
scoreboard players set @s score 0
scoreboard players set @s in_task 0
scoreboard players set @s teacher 0
scoreboard players set @s build_mode 0
scoreboard players set @s build_timer 0
scoreboard players set @s task_start_timer 0
scoreboard players set @s task_timer_act 0
scoreboard players set @s task_room_num 0
scoreboard players set @s task_player_num 0
scoreboard players set @s phone_selected 0
scoreboard players set @s task_lang 0
scoreboard players set @s task_0_sea 0
scoreboard players set @s task_0_crash 0
scoreboard players set @s task_0_seaS 0
scoreboard players set @s task_0_crashS 0
scoreboard players set @s task_0_done 0
scoreboard players set @s task_0_lang 0
scoreboard players set @s task_0-5_fon 0
scoreboard players set @s task_0-5_sews 0
scoreboard players set @s task_0-5_sewst 0
scoreboard players set @s task_1_done 0
scoreboard players set @s task_1_rs_1_done 0
scoreboard players set @s task_1_rs_2_done 0
scoreboard players set @s task_1_rs_3_done 0
scoreboard players set @s task_2_done 0
scoreboard players set @s task_2_prog 0
scoreboard players set @s task_3_done 0
scoreboard players set @s task_3_prog 0
scoreboard players set @s task_3_fail 0
scoreboard players set @s task_4_done 0
scoreboard players set @s task_4_prog 0
scoreboard players set @s task_4_start 0
scoreboard players set @s task_4_fail 0
scoreboard players set @s task_4_timer 0
scoreboard players set @s task_5_done 0
scoreboard players set @s task_5_timer 0
scoreboard players set @s task_5_clownfish 0
scoreboard players set @s task_5_pufferfis 0
scoreboard players set @s task_6_done 0
scoreboard players set @s task_6_prog 0
scoreboard players set @s task_6_start 0
scoreboard players set @s task_6_fail 0
scoreboard players set @s task_6_player 0
scoreboard players set @s task_7_done 0
scoreboard players set @s task_7_player 0
scoreboard players set @s task_8_done 0
scoreboard players set @s task_8_player 0
scoreboard players set @s p1_state_cur 0
scoreboard players set @s p1_state_prev 0
scoreboard players set @s p2_state_cur 0
scoreboard players set @s p2_state_prev 0
scoreboard players set @s update_signs 0
scoreboard players set @s crypto_score 0
scoreboard players set @s crypto_current 0
scoreboard players set @s crypto_cmplt_1 0
scoreboard players set @s crypto_cmplt_2 0
scoreboard players set @s crypto_cmplt_3 0
scoreboard players set @s crypto_cmplt_4 0
scoreboard players set @s crypto_cmplt_5 0
scoreboard players set @s crypto_v_done 0
scoreboard players set @s crypto_v_prog 0
scoreboard players set @s crypto_timer 0
scoreboard players set @s crypto_loc_show 0
scoreboard players set @s cine_timer_1 0
scoreboard players set @s cine_timer_2 0
scoreboard players set @s crypto_robot 0
scoreboard players set @s crypto_total 0
scoreboard players set @s crypto_v_test 0
scoreboard players set @s task0 0
scoreboard players set @s task1 0
scoreboard players set @s task2 0
scoreboard players set @s task3 0
scoreboard players set @s task4 0
scoreboard players set @s task5 0
scoreboard players set @s task6 0
scoreboard players set @s task7 0
scoreboard players set @s task8 0
scoreboard players set @s task_0-5_insew 0
scoreboard players set @s task_0-5_sewer 0
scoreboard players set @s task_0-5_sewpos 0
scoreboard players set @s task_0-5_ss 0
scoreboard players set @s task_0-5_sstimer 0
scoreboard players set @s task_0_timer 0
scoreboard players set @s task_5_prog 0
scoreboard players set @s task_5_start 0
scoreboard players set @s tick 0

title @s subtitle Seymour Island

title @s title Welcome to
tp @s -876 124 386 facing -876 124 388
